name: Run Crypto News Agent

on:
  schedule:
    # Runs at 7:00 AM (EST) every day
    - cron: '0 12 * * *'  # UTC time (12:00 UTC = 7:00 AM EST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-agent:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set environment variables
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: |
        # Copy .env.example to .env
        cp .env.example .env
        # Replace placeholders with actual values
        sed -i "s|YOUR_OPENAI_API_KEY|$OPENAI_API_KEY|g" .env
        sed -i "s|YOUR_NEWS_API_KEY|$NEWS_API_KEY|g" .env
    
    - name: Run the agent
      run: python main.py